public class ClassTestException {

	public void test(int x) throws ErreurValeurNegative {
		if (x<0) throw new ErreurValeurNégative();
	}
	
	public void test2(int y) throws ErreurValeurNegative {
		 try {
			 if (y<0) throw new ErreurValeurNegative();
		 }
		 catch(Exception e) {System.out.println(e);
		 
		 }
	}
}
